version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8.10
    commands:
    - cd utopiaReservation
    - echo im inside utopia
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - serverless deploy
    - echo im done